export const COURSES = [
    {
        "id": 2,
        "title": "Python with Django Training",
        "image": "https://mindrisers.com.np/static/Images/courses/python_p90ydK9.webp",
        "slug": "python-django-training-in-nepal",
        "banner": "https://mindrisers.com.np/static/Images/courses/banner/1.webp",
        "banner_desc": "Python Training course in Kathmandu, Nepal.",
        "description": "<p><span style=\"color:#0e101a\">Learn Python programming language in Nepal</span><span style=\"color:#0e101a\"> with our expert developers at Mindrisers from basic to advanced. A framework like Django, one of the most popular programming frameworks in this digital age is in every company&#39;s demand. We have </span><span style=\"color:#0e101a\">Python training courses in Nepal </span><span style=\"color:#0e101a\">with a practical learning environment where you get intense, in-depth practical project-based learning.</span></p>\r\n\r\n<p><br />\r\n<span style=\"color:#0e101a\">Mindrisers provides you with </span><span style=\"color:#0e101a\">Python training course</span><span style=\"color:#0e101a\"> from basic to advance with the guidance of experts. Within the course, you will have to work on a project using </span><span style=\"color:#0e101a\">Python</span><span style=\"color:#0e101a\">. The focus of the course is to critically engage students with intelligent approaches to creating interactive web apps using </span><span style=\"color:#0e101a\">Python.</span></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<h2><strong><span style=\"color:#0e101a\">Why Mindrisers for Python with Django Training in Nepal?</span>&nbsp;</strong></h2>\r\n\r\n<p><span style=\"color:#0e101a\">Experts as a tutor&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Project-based practical learning&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Certification after completion&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Internship and job placement included&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Online and Physical classes are available </span></p>\r\n\r\n<p>&nbsp;</p>",
        "duration": "2.5 months",
        "career": "Python Developer",
        "meta_tag": null,
        "status": "Publish"
    },
    {
        "id": 3,
        "title": "Graphic Design Training",
        "image": "https://mindrisers.com.np/static/Images/courses/Graphic.webp",
        "slug": "graphic-design-training-in-nepal",
        "banner": "https://mindrisers.com.np/static/Images/courses/banner/Untitled_design-48.webp",
        "banner_desc": "Graphic Design Training in Kathmandu, Nepal",
        "description": "<p>Mindrisers&nbsp;is offering you one of the most demanding courses,&nbsp;graphics design training in Nepal.&nbsp;Graphics designing&nbsp;is one of the most demanding careers in the sectors like marketing agencies, online media, advertising agencies, print media, website designing, and visual branding. Our expert&nbsp;graphic designers&nbsp;have designed this course for you in such a way that you will get intense, in-depth practical project-based learning which will skyrocket your career.&nbsp;</p>\r\n\r\n<p>Graphic design training in Nepal&nbsp;offered by&nbsp;Mindrisers&nbsp;is market-demand and career-oriented which will give you in-depth core knowledge about&nbsp;graphic design.&nbsp;&nbsp;During the&nbsp;graphic design training course, you will get in-depth practical knowledge about Adobe Photoshop, Adobe Illustrator, Adobe After Effects, Adobe InDesign, and many more.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<h2><strong><span style=\"color:#0e101a\">Why Mindrisers for Graphic Design Training in Nepal?</span></strong></h2>\r\n\r\n<p><span style=\"color:#0e101a\">Experts as a tutor&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Project-based practical learning&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Certification after completion&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Internship and job placement included&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Online and Physical class available </span></p>\r\n\r\n<p>&nbsp;</p>",
        "duration": "2.5 months",
        "career": "Graphic Designer",
        "meta_tag": null,
        "status": "Publish"
    },
    {
        "id": 4,
        "title": "Mern Stack Training",
        "image": "https://mindrisers.com.np/static/Images/courses/Mern_VtzmShy.webp",
        "slug": "mern-stack-development-training-in-nepal",
        "banner": "https://mindrisers.com.np/static/Images/courses/banner/Untitled_design-47_oFkinuM.webp",
        "banner_desc": "(Mern Stack) MongoDB, ExpressJS, ReactJS & Node.JS Training in Nepal",
        "description": "<p><span style=\"color:#0e101a\">Mindrisers is offering you </span><span style=\"color:#0e101a\">MERN STACK training in Nepal</span><span style=\"color:#0e101a\"> that aims to provide you with a strong base for the development of complex web applications. Our expert aims to provide you with expertise in </span><span style=\"color:#0e101a\">full-stack development with MongoDB, Express, React Js, and Node Js.</span></p>\r\n\r\n<h2>&nbsp;</h2>\r\n\r\n<h2><strong><span style=\"color:#0e101a\">Why Mindrisers for </span><span style=\"color:#0e101a\">MERN Stack Development Training in Nepal</span><span style=\"color:#0e101a\">?</span></strong></h2>\r\n\r\n<p><span style=\"color:#0e101a\">Experts as a tutor&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Project-based practical learning&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Certification after completion&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Internship and job placement included&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Online and Physical class are available&nbsp;</span></p>\r\n\r\n<p>&nbsp;</p>",
        "duration": "2.5 months",
        "career": "Mern Stack Developer",
        "meta_tag": null,
        "status": "Publish"
    },
    {
        "id": 5,
        "title": "Flutter Framework Training",
        "image": "https://mindrisers.com.np/static/Images/courses/Flutter_XhGz6P9.webp",
        "slug": "flutter-framework-training-in-nepal",
        "banner": "https://mindrisers.com.np/static/Images/courses/banner/3.webp",
        "banner_desc": "Flutter Framework Training in Kathmandu, Nepal",
        "description": "<p><span style=\"color:#0e101a\">Mindrisers is providing you </span><span style=\"color:#0e101a\">with Flutter framework training in Nepal</span><span style=\"color:#0e101a\">. </span><span style=\"color:#0e101a\">Flutter </span><span style=\"color:#0e101a\">is an open-source framework by google which is becoming most popular among those who are interested in building applications for Android and iOS using the </span><span style=\"color:#0e101a\">Dart programming language</span><span style=\"color:#0e101a\">. Our expert developers at </span><span style=\"color:#0e101a\">Mindrisers </span><span style=\"color:#0e101a\">provide you with practical project-based learning that meets the industry requirements.</span></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<h2><strong><span style=\"color:#0e101a\">Why Mindrisers for Flutter framework training in Nepal?</span></strong></h2>\r\n\r\n<p><span style=\"color:#0e101a\">Experts as a tutor&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Project-based practical learning&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Certification after completion&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Internship and job placement included&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Online and Physical class available&nbsp;</span></p>\r\n\r\n<p>&nbsp;</p>",
        "duration": "2.5 months",
        "career": "Flutter Developer",
        "meta_tag": null,
        "status": "Publish"
    },
    {
        "id": 6,
        "title": "Digital Marketing Training",
        "image": "https://mindrisers.com.np/static/Images/courses/Digital_0ouwxN3.webp",
        "slug": "digital-marketing-training-in-nepal",
        "banner": "https://mindrisers.com.np/static/Images/courses/banner/2.webp",
        "banner_desc": "Digital Marketing Training in Kathmandu, Nepal with SEO, SMM SEM Analytical tools and more training",
        "description": "<p><span style=\"color:#000000\">Mindrisers has been providing Digital Marketing training in Nepal under the guidance of our experts Digital Marketers. We provide you with intense, in-depth practical project-based learning in Digital Marketing in the fields like complete WordPress website development, Search Engine Optimization (SEO), Social Media Marketing (SMM), Search Engine Marketing (SEM), Graphic design with Canva, Analytical tools and many more.</span></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><span style=\"color:#000000\">Learning digital marketing at Mindrisers is the best option for those who want to develop their career as digital marketers because Mindrisers is also a digital marketing company where our expert digital marketers teach you about digital marketing.</span></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<h2><strong><span style=\"color:#0e101a\">Why Mindrisers for </span><span style=\"color:#0e101a\">Digital Marketing Training in Nepal</span><span style=\"color:#0e101a\">?</span></strong></h2>\r\n\r\n<p><span style=\"color:#0e101a\">Experts as a tutor&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Project-based practical learning&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Certification after completion&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Internship and job placement included&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Online and Physical classes are available&nbsp;</span></p>\r\n\r\n<p>&nbsp;</p>",
        "duration": "2.5 months",
        "career": "Digital Marketer",
        "meta_tag": null,
        "status": "Publish"
    },
    {
        "id": 7,
        "title": "Web Design and Development Training",
        "image": "https://mindrisers.com.np/static/Images/courses/web.webp",
        "slug": "web-design-training-in-nepal",
        "banner": "https://mindrisers.com.np/static/Images/courses/banner/6.webp",
        "banner_desc": "Web Design and Development Training in Nepal - HTML5, CSS3, JavaScript, React, JQuery, Bootstrap 5, SaSS / SCSS Training",
        "description": "<p><span style=\"color:#0e101a\">Learn web design and web development</span><span style=\"color:#0e101a\"> with an updated course that meets the industry requirements under the guidance of our experienced web designer and web developer at </span><span style=\"color:#0e101a\">Mindrisers</span><span style=\"color:#0e101a\">. We provide you with intense and project-based learning in HTML 5, CSS3, JavaScript, React JS, and web design with Bootstrap.</span></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<h2><strong><span style=\"color:#0e101a\">Why Mindrisers</span><span style=\"color:#0e101a\"> for Web Design and Development Training in Nepal?</span></strong></h2>\r\n\r\n<p><span style=\"color:#0e101a\">Experts as a tutor&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Project-based practical learning&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Certification after completion&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Internship and job placement included&nbsp;</span></p>\r\n\r\n<p><span style=\"color:#0e101a\">Online and Physical classes are available </span></p>\r\n\r\n<p>&nbsp;</p>",
        "duration": "2.5 months",
        "career": "Web Designer and Web Developer",
        "meta_tag": null,
        "status": "Publish"
    },
    {
        "id": 9,
        "title": "Python For Data Science Training in Nepal",
        "image": "https://mindrisers.com.np/static/Images/courses/Course_design.webp",
        "slug": "python-for-data-science-training-in-nepal",
        "banner": "https://mindrisers.com.np/static/Images/courses/banner/Untitled_design-50.webp",
        "banner_desc": "Data Science with Python Training",
        "description": "<p>Mindrisers is offering Data Science with Python training in Nepal for students who want to build their career as a data scientist. Data Science with Python is evolving and is one of the most demanding career. Mindrisers provides Data Science training with an expert tutor with practical and project-based learning. Data science is the study of data with the goal of gaining important business insights. It is a multidisciplinary method for analyzing massive volumes of data that integrates ideas and techniques from the domains of mathematics, statistics, artificial intelligence, and computer engineering. To learn Data Science with python training in Nepal, Mindrisers is here to provide you with quality and practical career-oriented training.<br />\r\n&nbsp;</p>\r\n\r\n<h2><strong>Why Mindrisers&nbsp;for Data Science with Python Training in Nepal?</strong></h2>\r\n\r\n<p>Experts as a tutor&nbsp;</p>\r\n\r\n<p>Project-based practical learning&nbsp;</p>\r\n\r\n<p>Certification after completion&nbsp;</p>\r\n\r\n<p>Internship and job placement included&nbsp;</p>\r\n\r\n<p>Online and Physical classes are available</p>",
        "duration": "2.5 months",
        "career": "Data Scientist",
        "meta_tag": null,
        "status": "Publish"
    },
    {
        "id": 10,
        "title": "UI/UX design training",
        "image": "https://mindrisers.com.np/static/Images/courses/Course_design-4.webp",
        "slug": "ui-ux-design-training-in-nepal",
        "banner": "https://mindrisers.com.np/static/Images/courses/banner/Untitled_design-52.webp",
        "banner_desc": "UI/UX Design Training in Kathmandu, Nepal",
        "description": "<p>Mindrisers is offering UI/UX design training in Nepal for aspiring students who want to build their career as UI/UX designers. The UI/UX design training offered by Mindrisers provides you with skills and knowledge in designing web/mobile apps. The course is career oriented and is in high demand in Nepal. UI/UX design training in Nepal is evolving as the increasing demand for UI/UX designers for the designing of web and mobile apps. Join Mindrisers UI/UX training and get a guaranteed internship and job placement.</p>",
        "duration": "2.5 months",
        "career": "UI/UX Designer",
        "meta_tag": "<p>&lt;meta&nbsp;name=&quot;description&quot;&nbsp;content=&quot;UI/UX design training&quot;&gt;<br />\r\n&nbsp;&nbsp;&lt;meta&nbsp;name=&quot;keywords&quot;&nbsp;content=&quot;UI/UX design training&quot;&gt;<br />\r\n&nbsp;&nbsp;&lt;meta&nbsp;name=&quot;author&quot;&nbsp;content=&quot;Mindrisers&quot;&gt;</p>",
        "status": "Publish"
    },
    {
        "id": 11,
        "title": "QA Training in Nepal",
        "image": "https://mindrisers.com.np/static/Images/courses/Course_design-5.webp",
        "slug": "quality-assurance-training-in-nepal",
        "banner": "https://mindrisers.com.np/static/Images/courses/banner/Untitled_design-54.webp",
        "banner_desc": "Quality Assurance Training in Kathmandu, Nepal",
        "description": "<p>In order to advance your career, Mindrisers is offering you the chance to receive Quality Assurance Training in Nepal. Demand for Quality Assurance training in software development has increased daily. We have experts and professionals who have been providing professional Quality Assurance Training in Nepal for software development. Here are a few reasons to enroll in quality assurance training at Mindrisers.</p>\r\n\r\n<ul>\r\n\t<li>Capable of finding errors in the application.</li>\r\n\t<li>The increasing market needs for software developers and software products.</li>\r\n\t<li>Enables you to construct faultless, well-performing software and applications.</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<h2>Why Mindrisers for Quality Assurance Training in Nepal?</h2>\r\n\r\n<ul>\r\n\t<li>Experts as a tutor&nbsp;</li>\r\n\t<li>Project-based practical learning&nbsp;</li>\r\n\t<li>Certification after completion&nbsp;</li>\r\n\t<li>Internship and job placement included&nbsp;</li>\r\n\t<li>Online and Physical classes are available&nbsp;</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>",
        "duration": "2.5 months",
        "career": "Quality Assurance (QA) Engineer",
        "meta_tag": "<p>tag</p>",
        "status": "Publish"
    }
]