import dynamic from 'next/dynamic'
import Head from 'next/head'
import React from 'react'
import Gallery from '../components/HomePageComponents/Gallery'
import HomeAboutUs from "../components/HomePageComponents/HomeAboutUs"
import HomeContact from '../components/HomePageComponents/HomeContact'
import HomeSuccessStories from '../components/HomePageComponents/HomeSuccessStories'
import Jumpstart from "../components/HomePageComponents/Jumpstart"
import Mission from "../components/HomePageComponents/Mission"
import Splash from "../components/HomePageComponents/Splash"
import TrainingsHomePage from "../components/HomePageComponents/TrainingsHomePage"

export default function Home() {
  const TestimonialNoSsr = dynamic(
    () => import("../components/HomePageComponents/Testimonials"),
    { ssr: false }
  )
  return (
    <div >
      <Head>
        <title>Mind Risers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className='text-gray-800' > */}
      <main>
        <Splash />
        <TrainingsHomePage />
        <HomeAboutUs />
        <Mission />
        {/* <OurServices /> */}
        <Gallery />
        <HomeContact />
        <HomeSuccessStories />
        {/* <Statistics /> */}
        <Jumpstart />
        <TestimonialNoSsr />
      </main>

    </div>
  )
}
