import dynamic from 'next/dynamic'
import Head from 'next/head'
import React from 'react'
import HomeAboutUs from "../components/HomePageComponents/HomeAboutUs"
import Jumpstart from "../components/HomePageComponents/Jumpstart"
import Mission from "../components/HomePageComponents/Mission"
import OurServices from "../components/HomePageComponents/OurServices.tsx"
import Splash from "../components/HomePageComponents/Splash"
import Statistics from "../components/HomePageComponents/Statistics"
import Testimonials from "../components/HomePageComponents/Testimonials"
import TrainingsHomePage from "../components/HomePageComponents/TrainingsHomePage"

export default function Home() {
  const TestimonialNoSsr = dynamic(
    () => import("../components/HomePageComponents/Testimonials"),
    { ssr: false }
  )
  return (
    <div >
      <Head>
        <title>Mind Risers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Splash />
        <TrainingsHomePage />
        <HomeAboutUs />
        <Mission />
        <OurServices />
        <Statistics />
        <Jumpstart />
        <TestimonialNoSsr />
      </main>

    </div>
  )
}
