import Head from 'next/head'
import React, { Suspense, useEffect } from 'react'
import Header from "../components/HeaderComponents/Header"
import Footer from "../components/FooterComponents/Footer"
import Splash from "../components/HomePageComponents/Splash"
import HomeAboutUs from "../components/HomePageComponents/HomeAboutUs"
import TrainingsHomePage from "../components/HomePageComponents/TrainingsHomePage"
import publicRequest from './api/requestMethods'

export default function Home() {

  return (
    <div >
      <Head>
        <title>Mind Risers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Header />
        <Splash />
        <TrainingsHomePage publicRequest={publicRequest} />
        <HomeAboutUs />
        {/* <Suspense fallback={<div>Loading...</div>}> */}
        {/* <Mission /> */}
        {/* <OurServices /> */}
        {/* <Statistics /> */}
        {/* <Jumpstart /> */}
        {/* <Testimonials /> */}
        {/* </Suspense> */}
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  )
}
