name: Build and Merge

on:
    push:
        branches:
            - new-ui # Change this to your branch name

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20.9.x"
            # Add steps to build your code here
            # For example, if it's a Node.js project:
            - name: Install dependencies and build
              run: |
                  npm install
                  npm run build

            # Merge to a branch (for example, 'main')
            - name: Merge to production
              run: |
                  git checkout production
                  git merge ${{ github.ref }}

            # Push the changes back to the repository
            - name: Push changes
              run: |
                  git push origin production
